# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81e11d0adce2c33a0bc5e2d9f44b57a985e00c20a4a7177c24a6be1d3779bd44e253fa94d2fb6369adf58a61c8db92b79454a3afec75f358eac4a8bc201503a4

test:
  secret_key_base: beeb4f7da5d792bd071557206f9c075fdc43e17aa429df7acb868637a558a84a2b82c2b5251ebf837909c8e5f0d921a983e94bdc9e68675032216489f000ef23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
